/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MailRouteImport } from './routes/mail'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/mail': typeof MailRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/payments': typeof PaymentsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/university': typeof UniversityRoute
  '/website': typeof WebsiteRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/mail': typeof MailRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/payments': typeof PaymentsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/university': typeof UniversityRoute
  '/website': typeof WebsiteRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/mail': typeof MailRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/payments': typeof PaymentsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/university': typeof UniversityRoute
  '/website': typeof WebsiteRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/mail'
    | '/onboarding'
    | '/parents'
    | '/payments'
    | '/results'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/university'
    | '/website'
    | '/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/mail'
    | '/onboarding'
    | '/parents'
    | '/payments'
    | '/results'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/university'
    | '/website'
    | '/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/mail'
    | '/onboarding'
    | '/parents'
    | '/payments'
    | '/results'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/university'
    | '/website'
    | '/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRoute
  CommunicationRoute: typeof CommunicationRoute
  DashboardRoute: typeof DashboardRoute
  MailRoute: typeof MailRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentsRoute: typeof ParentsRoute
  PaymentsRoute: typeof PaymentsRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  TeachersRoute: typeof TeachersRoute
  TimetableRoute: typeof TimetableRoute
  UniversityRoute: typeof UniversityRoute
  WebsiteRoute: typeof WebsiteRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRoute,
  CommunicationRoute: CommunicationRoute,
  DashboardRoute: DashboardRoute,
  MailRoute: MailRoute,
  OnboardingRoute: OnboardingRoute,
  ParentsRoute: ParentsRoute,
  PaymentsRoute: PaymentsRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  TeachersRoute: TeachersRoute,
  TimetableRoute: TimetableRoute,
  UniversityRoute: UniversityRoute,
  WebsiteRoute: WebsiteRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
